// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UMKM_C_.Data;

#nullable disable

namespace UMKM_C_.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241206025932_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UMKM_C_.Models.Bahan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("created_at")
                        .HasColumnType("longtext");

                    b.Property<int?>("harga")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("jumlah")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("nama")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Bahan");
                });

            modelBuilder.Entity("UMKM_C_.Models.Pemasukan_bulanan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bulan")
                        .HasColumnType("int");

                    b.Property<int>("HarianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HarianId");

                    b.ToTable("Pemasukan_bulanan");
                });

            modelBuilder.Entity("UMKM_C_.Models.Pemasukan_harian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_at")
                        .HasColumnType("longtext");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<string>("Updated_at")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pemasukan_harian");
                });

            modelBuilder.Entity("UMKM_C_.Models.Pengeluaran_bulanan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bulan")
                        .HasColumnType("int");

                    b.Property<int>("HarianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HarianId");

                    b.ToTable("Pengeluaran_bulanan");
                });

            modelBuilder.Entity("UMKM_C_.Models.Pengeluaran_harian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_at")
                        .HasColumnType("longtext");

                    b.Property<int?>("Harga")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Jumlah")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Updated_at")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pengeluaran_harian");
                });

            modelBuilder.Entity("UMKM_C_.Models.Pemasukan_bulanan", b =>
                {
                    b.HasOne("UMKM_C_.Models.Pemasukan_harian", "Pemasukan_harian")
                        .WithMany("Pemasukan_bulanan")
                        .HasForeignKey("HarianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pemasukan_harian");
                });

            modelBuilder.Entity("UMKM_C_.Models.Pengeluaran_bulanan", b =>
                {
                    b.HasOne("UMKM_C_.Models.Pengeluaran_harian", "Pengeluaran_harian")
                        .WithMany("Pengeluaran_bulanan")
                        .HasForeignKey("HarianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pengeluaran_harian");
                });

            modelBuilder.Entity("UMKM_C_.Models.Pemasukan_harian", b =>
                {
                    b.Navigation("Pemasukan_bulanan");
                });

            modelBuilder.Entity("UMKM_C_.Models.Pengeluaran_harian", b =>
                {
                    b.Navigation("Pengeluaran_bulanan");
                });
#pragma warning restore 612, 618
        }
    }
}
